{% set version = "1.2.0" %}

package:
  name: involucro
  version: {{ version }}

source:
  - url: https://github.com/involucro/involucro/archive/v{{ version }}.tar.gz
    sha256: 37b5f05eed105b53762b274e0fc78f0a61497dea11ee2dc9b4586c59bde65971
    folder: src/github.com/involucro/involucro

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses
  host:
  run:

test:
  commands:
    - involucro --help
    - involucro --version | grep -qF {{ version }}

about:
  home: https://github.com/involucro/involucro
  license: Apache-2.0
  license_file:
    - src/github.com/involucro/involucro/NOTICE.md
    - src/github.com/involucro/involucro/LICENSE
    # Collect 3rd party licenses which generates in build.sh
    - src/github.com/involucro/involucro/3rd_party_license/
  summary: Build and Deliver Software with Containers

extra:
  recipe-maintainers:
    - bgruening
