{% set version = "1.3.0" %}

package:
  name: involucro
  version: {{ version }}

source:
  - url: https://github.com/involucro/involucro/archive/v{{ version }}.tar.gz
    sha256: d15b6432ca7c244e9cb9f6e08501cd2a8c8961454478c4eb545ef8ed09748960
    folder: src/github.com/involucro/involucro

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses
  host:
  run:

test:
  commands:
    - involucro --help
    - involucro --version | grep -qF {{ version }}

about:
  home: https://github.com/involucro/involucro
  license: Apache-2.0
  license_file:
    - src/github.com/involucro/involucro/NOTICE.md
    - src/github.com/involucro/involucro/LICENSE
    # Collect 3rd party licenses which generates in build.sh
    - src/github.com/involucro/involucro/3rd_party_license/
  summary: Build and Deliver Software with Containers

extra:
  recipe-maintainers:
    - bgruening
